import type { StoryDefinition } from "../abstractions/story-definition";

export const fogHarborMystery: StoryDefinition = {
  id: "fog-harbor-mystery",
  version: "1.0.0",
  title: "雾港疑云",
  description: "哥特悬疑慢热故事：外乡侦探追查失踪姐姐在雾港留下的痕迹。",
  premise: "雾港终年潮湿，旧港口的雾和白鲸酒馆的灯都藏着失踪者的秘密。",
  genre: ["gothic", "mystery"],
  tone: ["slow-burn", "suspense"],
  writingStyle: "克制、细节导向，以环境和对话推动悬疑。",
  playerRole: {
    identity: "寻找失踪姐姐的外乡侦探",
    knownFacts: ["姐姐最后一封信来自雾港", "白鲸酒馆被反复提及"],
  },
  characters: [
    {
      id: "evelyn",
      name: "伊芙琳",
      description: "白鲸酒馆老板娘，熟悉雾港所有传闻。",
      personality: ["谨慎", "敏锐", "不轻易信任外乡人"],
      speakingStyle: "短句、带试探，偶尔用酒馆隐喻。",
      publicBackground: "她继承了白鲸酒馆，并把它经营成港口消息的交汇处。",
      privateBackground: "她见过玩家姐姐，但不确定该说出多少。",
      secrets: [
        {
          id: "evelyn-saw-sister",
          summary: "伊芙琳曾在雨夜见过玩家姐姐。",
          loreId: "sister-at-tavern",
        },
      ],
      goals: ["保护酒馆", "避免旧港口势力注意到玩家"],
      fears: ["姐姐失踪案牵出旧案"],
      narrativeRole: "companion",
    },
    {
      id: "leon",
      name: "莱昂",
      description: "雾港警探，表面冷淡但仍在追查旧港口失踪案。",
      personality: ["严肃", "疲惫", "守规矩"],
      speakingStyle: "像写报告一样简洁。",
      publicBackground: "负责旧港口巡查，多次警告外乡人远离夜雾。",
      goals: ["控制调查风险", "找到能上报的证据"],
      narrativeRole: "supporting",
    },
    {
      id: "samuel",
      name: "塞缪尔",
      description: "医生，熟悉港口工人的伤病和沉默。",
      personality: ["温和", "回避冲突"],
      speakingStyle: "缓慢、谨慎，常先确认对方意图。",
      publicBackground: "在旧街诊所工作，曾为失踪者开过镇静药。",
      goals: ["不让无辜者受伤"],
      narrativeRole: "supporting",
    },
  ],
  scenes: [
    {
      id: "white-whale-tavern",
      title: "白鲸酒馆",
      description: "潮气沿木地板爬升，柜台后的煤油灯把每张脸照得像旧照片。",
      location: "雾港旧街",
      availableCharacterIds: ["evelyn", "leon"],
      eventIds: ["first-ask-evelyn-about-sister"],
    },
    {
      id: "old-harbor",
      title: "旧港口",
      description: "废弃吊机在雾中像沉默的骨架，潮声盖过远处的脚步。",
      location: "雾港海堤",
      availableCharacterIds: ["leon", "samuel"],
      entryConditions: [{ type: "has_item", itemId: "old-harbor-pass" }],
      eventIds: ["entered-old-harbor"],
    },
  ],
  lore: [
    {
      id: "fog-harbor-overview",
      title: "雾港传闻",
      content: "雾港居民相信夜雾会吞掉没有归处的人。",
      activation: "always",
      priority: 1,
    },
    {
      id: "sister-at-tavern",
      title: "姐姐到过白鲸酒馆",
      content: "伊芙琳认得玩家姐姐，也记得她点过蓝色月光。",
      keywords: ["姐姐", "失踪", "白鲸", "酒馆"],
      sceneIds: ["white-whale-tavern"],
      characterIds: ["evelyn"],
      activation: "keyword",
      priority: 10,
    },
    {
      id: "blue-wax",
      title: "蓝色蜡迹",
      content: "旧港口通行证的封蜡会留下暗蓝痕迹。",
      keywords: ["蜡", "蓝色", "通行证"],
      activation: "keyword",
      priority: 5,
    },
    {
      id: "hidden-smuggler-route",
      title: "隐藏走私路线",
      content: "旧港口三号码头后有一条绕过巡逻的窄路。",
      activation: "always",
      secret: true,
      priority: 100,
    },
  ],
  items: [
    {
      id: "blue-moon-menu",
      name: "蓝色月光酒单",
      description: "边角有被指甲刮出的细小记号。",
    },
    {
      id: "old-harbor-pass",
      name: "旧港口通行证",
      description: "封蜡处残留一圈暗蓝痕迹。",
    },
  ],
  clues: [
    {
      id: "menu-mark",
      title: "酒单上的记号",
      description: "记号指向酒单背面一行几乎褪色的日期。",
    },
    {
      id: "blue-wax-stain",
      title: "蓝色蜡迹",
      description: "这种封蜡只在旧港口仓库使用。",
    },
    {
      id: "sister-visited-tavern",
      title: "姐姐曾到过白鲸酒馆",
      description: "伊芙琳承认她曾见过玩家姐姐。",
    },
  ],
  events: [
    {
      id: "first-ask-evelyn-about-sister",
      title: "首次与伊芙琳谈及姐姐",
    },
    {
      id: "entered-old-harbor",
      title: "进入旧港口",
    },
  ],
  openingSceneId: "white-whale-tavern",
  openingText: "你推开白鲸酒馆的门，雾气跟着你一起涌入。伊芙琳抬眼，看见你手里那封潮湿的信。",
  attributes: [
    {
      key: "clueHeat",
      label: "调查热度",
      type: "number",
      scope: "story",
      required: true,
      default: 0,
      min: 0,
      max: 100,
      showInSidebar: true,
    },
    {
      key: "trust",
      label: "信任度",
      type: "number",
      scope: "character",
      characterIds: ["evelyn"],
      required: true,
      default: 0,
      min: -10,
      max: 10,
      showInSidebar: true,
    },
    {
      key: "publicTitle",
      label: "公开称号",
      type: "string",
      scope: "player",
      required: true,
      default: "外乡侦探",
      maxLength: 40,
      writable: false,
      showInSidebar: true,
    },
  ],
  relationshipsEnabled: false,
  narrativeRules: {
    mustFollow: ["状态变化必须来自已验证的 StoryTurnPlan", "悬疑信息逐步揭示"],
    mustAvoid: ["提前揭露隐藏路线", "让未在场角色发言"],
    pov: "second-person",
    responseLengthHint: "medium",
  },
};
